name: Cleanup

on:
    push:
    schedule:
        - cron: '0 3 * * *'
    workflow_dispatch:
        inputs:
            days_old:
                description: 'Delete cancelled runs older than X days'
                required: false
                default: '30'

jobs:
    cleanup:
        runs-on: ubuntu-latest
        steps:
            - name: Cleanup specific workflow
              run: |
                  DAYS_OLD=${INPUT_DAYS_OLD:-30}
                  CUTOFF_DATE=$(date -d "$DAYS_OLD days ago" +%Y-%m-%dT%H:%M:%SZ)

                  # 获取特定工作流的ID
                  workflow_id=$(gh api repos/${{ github.repository }}/actions/workflows --jq '.workflows[] | select(.name == "Detect") | .id')

                  # 原始代码添加统计
                  RUN_IDS=$(gh api "repos/${{ github.repository }}/actions/workflows/$workflow_id/runs?created=<$CUTOFF_DATE" \
                    --paginate \
                    --jq ".workflow_runs[] | select(.conclusion == \"cancelled\") | .id")

                  COUNT=$(echo "$RUN_IDS" | wc -w)

                  echo "Deleting $COUNT cancelled runs older than $DAYS_OLD days (before $CUTOFF_DATE) from workflow ID: $workflow_id..."

                  # 使用循环而不是xargs以便计数
                  DELETED=0
                  for id in $RUN_IDS; do
                    gh api repos/${{ github.repository }}/actions/runs/$id -X DELETE
                    DELETED=$((DELETED + 1))
                  done

                  echo "Deleted $DELETED cancelled runs"
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
