name: Cleanup

on:
    push:
    schedule:
        - cron: '* 6 * * *'
    workflow_dispatch:

jobs:
    cleanup:
        runs-on: ubuntu-latest
        steps:
            - name: Cleanup specific workflow
              run: |
                  # 获取特定工作流的ID
                  workflow_id=$(gh api repos/${{ github.repository }}/actions/workflows --jq '.workflows[] | select(.name == "Detect") | .id')

                  MAX_PARALLEL=10  # 根据API限制调整并行度

                  gh api "repos/${{ github.repository }}/actions/workflows/$workflow_id/runs?per_page=100" \
                    --paginate \
                    --jq ".workflow_runs[] | select(.conclusion == \"cancelled\") | .id" \
                    | xargs -P $MAX_PARALLEL -I {} bash -c '
                        gh api repos/${{ github.repository }}/actions/runs/{} -X DELETE --silent
                      '
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
